#!/bin/bash
# Date: Sun Sep  8 10:22:41 2019
# Author: January
set -o errexit

start_script_dir=~/.start
profile_path=~/.profile

run_start_script=$(cat << eof
# run startup script in $start_script_dir
if [ -d "$start_script_dir" ]; then
    dir="$start_script_dir"
    for script in `ls \$dir`
    do
        if [ -x "\$dir/\$script" ]; then
            \$dir/\$script
        fi
    done
fi
# code generated by January's script
eof
)

if [ -d $start_script_dir ]; then
    echo "directory $start_script_dir already exists"
    # 字符串比较时最好都加上引号，避免特殊符号引起的问题
    if [ "$1" != "-f" ]; then
        echo "aborting..."
        exit -1
    else
        echo "use existing diretory $start_script_dir"
    fi
else
    mkdir $start_script_dir
fi

already_put_script=$(cat $profile_path | grep "code generated by January's script") || true
if [ -z "$already_put_script" ]; then
    echo "puting script into $profile_path..."
    # 使用双引号包围变量可已让echo输出变量中的换行符
    echo "$run_start_script" >> $profile_path
else
    echo "script has already been added, no need to do again"
fi

echo "ok"
echo "Now, you can put the scripts that should be run when staring
into $start_script_dir and they will be executed automatically 
everytime you start your computer. "

